version: '3'

services:
  db_postgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./ops/docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: mydb
    hostname: postgres
    user: root

  schemaspy_postgresql:
    build:
      context: ops/docker
      dockerfile: ./schemaspy/Dockerfile
    volumes:
      - ./ops/docker/schemaspy/output/postgresql:/output
      - ./ops/docker/schemaspy/config:/config
    container_name: "schemaspy_local_postgresql"
    command: [ "-all", "-configFile", "/config/postgresql/schemaspy.properties" ]
    links:
      - db_postgresql

  wiki_db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wiki
      MYSQL_PASSWORD: wikijsrocks
      MYSQL_USER: wikijs
      TZ: 'Asia/Tokyo'
    volumes:
      - wiki-db-data:/var/lib/mysql
      - ./ops/docker/wiki/dump:/dump
    ports:
      - "3306:3306"

  wiki:
    image: ghcr.io/requarks/wiki:2
    environment:
      DB_TYPE: mysql
      DB_HOST: wiki_db
      DB_PORT: 3306
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    links:
      - wiki_db
      - plantuml
    ports:
      - "80:3000"

  plantuml:
    image: plantuml/plantuml-server:jetty
    environment:
      BASE_URL: plantuml
    ports:
      - "9999:8080"

  mkdocs:
    build:
      context: .
      dockerfile: ./ops/docker/mkdocs/Dockerfile
    volumes:
      - ./docs/wiki:/docs/docs
      - ./mkdocs.yml:/docs/mkdocs.yml
    ports:
      - "8000:8000"
    command: mkdocs serve --dev-addr=0.0.0.0:8000
    links:
      - plantuml

volumes:
  mysql8-data:
  postgresql-data:
  wiki-db-data:
