site_name: Go-DDD Wiki
site_description: Documentation for the Go-DDD project
site_author: Project Team
repo_url: https://github.com/yourusername/go-ddd
repo_name: go-ddd

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

extra_css:
  - wiki/assets/css/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
      format: svg

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - wiki/assets/js/extra.js

extra:
  plantuml_url: http://www.plantuml.com/plantuml
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/go-ddd
      name: GitHub Repository

plugins:
  - search

nav:
  - Home: home.md
  - Architecture: architecture.md
  - Features: feature_list.md
  - User Stories: user_stories.md
  - Planning:
    - Release Plan: release_plan.md
    - Iteration Plan: iteration_plan.md
  - Implementation:
    - System: system_implementation.md
    - Product: product_implementation.md
    - Seller: seller_implementation.md
    - ORM Mapper: orm_mapper_implementation.md
  - Setup:
    - Setup Guide: setup_guide.md
    - Setup Guide (Mermaid): setup_guide_mermaid.md
  - Documentation:
    - Documentation Summary: documentation_summary.md
    - Revision Summary: revision_summary.md
